import { Button } from '@chakra-ui/react';
import Head from 'next/head'
import { useRouter } from 'next/router';

export default function Home() {
  const router = useRouter();

  return (
    <div>
      <Head>
        <title>Travel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <p>2022年</p>
          <Button onClick={() => router.push('/okinawa')}>
            2022年9月　沖縄旅行
          </Button>
          <Button onClick={() => router.push('/hokkaido')}>
            2022年10月　北海道旅行
          </Button>
        </div>
      </main>
    </div>
  )
}
